[package]
name = "some-lib-forms"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false
autobins = false
autolib = false

[[bin]]
name = "some-lib-forms"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[[example]]
name = "demo"
path = "examples/demo.rs"

[dependencies]
chrono = { workspace = true }
gpui-kit = { workspace = true }
gpui-es-fluent = { workspace = true }
gpui-form = { workspace = true }
gpui-form-collection = { workspace = true }
gpui-form-component = { workspace = true }
gpui-storybook = { features = [ "macros" ], workspace = true }
rust_decimal = { workspace = true }
some-lib = { path = "../some-lib" }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dev-dependencies]
gpui-kit = { features = [ "test-support" ], workspace = true }

[lints]
workspace = true
