[package]
name = "gpui-form-component-story"
description = """
Storybook gallery for gpui-form-component runtime helpers
"""
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
readme = "README.md"

[dependencies]
es-fluent = { workspace = true }
es-fluent-lang = { workspace = true }
es-fluent-manager-embedded = { workspace = true }
gpui-kit = { workspace = true }
gpui-es-fluent = { workspace = true }
gpui-form-component = { features = [ "derive" ], workspace = true }
gpui-storybook = { features = [ "macros" ], workspace = true }
jiff = { workspace = true }
strum = { workspace = true }

[build-dependencies]
es-fluent-build = { workspace = true }

[dev-dependencies]
gpui-kit = { features = [ "test-support" ], workspace = true }
unic-langid = { workspace = true }

[lints]
workspace = true
