[package]
name = "gpui-form"
description = """
The gpui-form crate
"""
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
readme = "README.md"
keywords = [ "gpui", "gpui-component", "form" ]

[features]
default = [ "derive", "runtime" ]
derive = [ "dep:gpui-form-derive" ]
inventory = [ "gpui-form-derive?/inventory" ]
mcp = [ "dep:gpui-form-mcp", "inventory", "gpui-form-derive?/mcp" ]
runtime = [ "dep:gpui-form-runtime" ]

[dependencies]
bon = { workspace = true }
gpui-form-core = { workspace = true }
gpui-form-derive = { optional = true, workspace = true }
gpui-form-mcp = { optional = true, workspace = true }
gpui-form-runtime = { optional = true, workspace = true }
gpui-form-schema = { workspace = true }

[dev-dependencies]
gpui = { workspace = true }
gpui-form-collection = { workspace = true }
koruma = { workspace = true }
koruma-collection = { workspace = true }
serde = { features = [ "derive" ], workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
